Ong-gi-Jong-gi/namanmoo-backend

build.gradle, src/main/java/ongjong/namanmoo/domain/Family.java, src/main/java/ongjong/namanmoo/domain/Object.java, src/main/java/ongjong/namanmoo/domain/User.java, src/main/java/ongjong/namanmoo/domain/VoiceMessage.java, src/main/java/ongjong/namanmoo/domain/answer/Answer.java, src/main/java/ongjong/namanmoo/domain/answer/FaceTimeA.java, src/main/java/ongjong/namanmoo/domain/answer/GroupA.java, src/main/java/ongjong/namanmoo/domain/answer/NormalA.java, src/main/java/ongjong/namanmoo/domain/answer/PhotoA.java, src/main/java/ongjong/namanmoo/domain/answer/VoiceA.java, src/main/java/ongjong/namanmoo/domain/challenge/Challenge.java, src/main/java/ongjong/namanmoo/domain/challenge/FaceTime.java, src/main/java/ongjong/namanmoo/domain/challenge/Group.java, src/main/java/ongjong/namanmoo/domain/challenge/Normal.java, src/main/java/ongjong/namanmoo/domain/challenge/Photo.java, src/main/java/ongjong/namanmoo/domain/challenge/Voice.java
=> [TSK-14] : 도메인 설계

src/main/java/ongjong/namanmoo/domain/Member.java, src/main/resources/application.yml
=> Feature/tsk 5/login out signup

.github/workflows/Spring Boot CI-CD
=> setting : Create Spring Boot CI-CD.yml

.github/workflows /Spring Boot CI-CD
=> [TSK-4] Spring Boot CI/CD with Docker and EC2

.gitignore, src/main/java/ongjong/namanmoo/config/AwsS3Config.java
=> 🚨 CORS 설정 

src/main/java/ongjong/namanmoo/global/security/config/CorsConfig.java
=> 🚨 인증 토큰 노출

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/MemberController.java, src/main/java/ongjong/namanmoo/global/exception/handler/GlobalExceptionHandler.java, src/main/java/ongjong/namanmoo/service/AwsS3Service.java
=> ⚠️AWS S3 업로드 관련 로그 추가

src/main/java/ongjong/namanmoo/controller/MemberController.java
=> 유저 사진 업데이트 수정

src/main/java/ongjong/namanmoo/global/security/handler/LoginSuccessJWTProvideHandler.java
=> [TSK-35] : 행운이 상태, 말풍선 로직 구현

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/AnswerService.java, src/main/java/ongjong/namanmoo/service/ChallengeService.java
=> fix: get challenge modify

src/main/java/ongjong/namanmoo/dto/answer/AnswerDto.java
=> fix: userid

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/FamilyController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/domain/ChallengeLength.java, src/main/java/ongjong/namanmoo/domain/Lucky.java, src/main/java/ongjong/namanmoo/domain/Member.java, src/main/java/ongjong/namanmoo/domain/MemberRole.java, src/main/java/ongjong/namanmoo/domain/challenge/Challenge.java, src/main/java/ongjong/namanmoo/dto/answer/AnswerDto.java, src/main/java/ongjong/namanmoo/dto/challenge/ChallengeDto.java, src/main/java/ongjong/namanmoo/dto/lucky/LuckyListDto.java, src/main/java/ongjong/namanmoo/repository/ChallengeRepository.java, src/main/java/ongjong/namanmoo/service/AnswerService.java, src/main/java/ongjong/namanmoo/service/ChallengeDataInit.java, src/main/java/ongjong/namanmoo/service/ChallengeService.java, src/main/java/ongjong/namanmoo/service/DateUtil.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java, src/test/java/ongjong/namanmoo/global/security/filter/JwtAuthenticationProcessingFilterTest.java, src/test/java/ongjong/namanmoo/global/security/jwt/service/JwtServiceImplTest.java, src/test/java/ongjong/namanmoo/repository/MemberRepositoryTest.java, src/test/java/ongjong/namanmoo/service/LoginServiceTest.java
=> [TSK-36] 행운이 리스트 조회 API

src/main/java/ongjong/namanmoo/dto/answer/AnswerDto.java
=> chore : fix getMemberId -> getLoginId in AnswerDto

src/main/java/ongjong/namanmoo/controller/ChallengeController.java
=> Chore : fix RequestPart -> RequestParam

src/main/java/ongjong/namanmoo/domain/Lucky.java, src/main/java/ongjong/namanmoo/domain/VoiceMessage.java, src/main/java/ongjong/namanmoo/domain/answer/Answer.java, src/main/java/ongjong/namanmoo/domain/answer/FaceTimeAnswer.java, src/main/java/ongjong/namanmoo/global/security/config/CorsConfig.java, src/main/java/ongjong/namanmoo/service/AwsS3Service.java
=> ⚠️ CORS domain update & S3 directory for FileType

src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/dto/lucky/LuckyListDto.java, src/main/java/ongjong/namanmoo/global/security/config/CorsConfig.java, src/main/java/ongjong/namanmoo/service/LuckyService.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> CORS domain update

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/dto/challenge/GroupChallengeDto.java, src/main/java/ongjong/namanmoo/dto/recapMember/MemberYouthAnswerDto.java, src/main/java/ongjong/namanmoo/service/AnswerService.java, src/main/java/ongjong/namanmoo/service/ChallengeService.java, src/main/java/ongjong/namanmoo/service/MemberService.java, src/main/java/ongjong/namanmoo/service/MemberServiceImpl.java
=> feat: recap youth complete

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java
=> Feature/tsk 50/recap photos

src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/service/AwsS3Service.java
=> RECAP youth/appreciations 챌린지 번호 임시 변경

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/domain/challenge/ChallengeType.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/ChallengeDataInit.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java
=> Feature/tsk 41/recap facetime

build.gradle, src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/domain/SharedFile.java, src/main/java/ongjong/namanmoo/domain/challenge/ChallengeType.java, src/main/java/ongjong/namanmoo/repository/SharedFileRepository.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/AwsS3Service.java, src/main/java/ongjong/namanmoo/service/ChallengeDataInit.java, src/main/java/ongjong/namanmoo/service/ImageMerger.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java, src/main/resources/application-jwt.yml
=> [TSK-39] 인생네컷 이미지 저장 및 병합, 비디오 저장

src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-39] 인생 네컷 사진 저장 수정

src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/dto/recap/MemberFacetimeDto.java, src/main/java/ongjong/namanmoo/dto/recap/MemberPhotosAnswerDto.java, src/main/java/ongjong/namanmoo/dto/recap/MemberYouthAnswerDto.java, src/main/java/ongjong/namanmoo/repository/FamilyRepository.java, src/main/java/ongjong/namanmoo/repository/LuckyRepository.java, src/main/java/ongjong/namanmoo/service/AnswerService.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java, src/main/java/ongjong/namanmoo/service/FamilyServiceImpl.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> Recap Youth Error Modify

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/ImageMerger.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-39] 화상 챌린지 인생네컷

src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-39] 인생네컷 챌린지 결과 조회 수정

src/main/java/ongjong/namanmoo/global/security/config/SecurityConfig.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> [TSK-34] 로그아웃, 말풍선 구현

src/main/java/ongjong/namanmoo/global/security/config/SecurityConfig.java
=> [TSK-34] 로그아웃 url 변경

.github/workflows/Spring Boot CI-CD.yml, Dockerfile, docker-compose.yml, src/main/resources/application.yml
=> [TSK-52] Set S3 region and updated jar filename in Dockerfile

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/domain/Lucky.java, src/main/java/ongjong/namanmoo/dto/challenge/VoiceChallengeDto.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java, src/main/resources/application-jwt.yml
=> [TSK-53] 챌린지 조회/수정 타입 체크 로직 추가

src/main/java/ongjong/namanmoo/controller/ChallengeController.java
=> [TSK-53] Refactor ChallengeController by Extracting Validation Methods

src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java
그냥 해당하는 답변 테이블이 있으면답변이 있다고 간주 되었었는데, 답변 내용이 NULL인지 확인하는 로직 추가
=> [TSK-53] 리캡 통계 수정

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/FamilyController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/repository/MemberRepository.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java, src/main/java/ongjong/namanmoo/service/FamilyServiceImpl.java
=> [TSK-54] voice and family error modify

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/LuckyController.java, src/main/java/ongjong/namanmoo/dto/lucky/CurrentLuckyDto.java, src/main/java/ongjong/namanmoo/service/FamilyServiceImpl.java
=> [TSK-54] feat challenge startdate

src/main/java/ongjong/namanmoo/config/FFmpegConfig.java, src/main/java/ongjong/namanmoo/config/OpenAiConfig.java, src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/domain/challenge/ChallengeType.java, src/main/java/ongjong/namanmoo/dto/openAI/TranscriptionRequest.java, src/main/java/ongjong/namanmoo/dto/openAI/WhisperTranscriptionResponse.java, src/main/java/ongjong/namanmoo/global/security/util/CustomMultipartFile.java, src/main/java/ongjong/namanmoo/repository/MemberRepository.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/AwsS3Service.java, src/main/java/ongjong/namanmoo/service/FFmpegService.java, src/main/java/ongjong/namanmoo/service/OpenAIClientService.java, src/main/resources/application.yml
=> [TSK-34] Whisper Ai, 음성 분할 구현

src/main/java/ongjong/namanmoo/config/OpenAiConfig.java
=> ⚠️ OPENAI_API_KEY env setting

.github/workflows/Spring Boot CI-CD.yml
=> 🚨 OPENAI_API_KEY env setting

.github/workflows/Spring Boot CI-CD.yml, Dockerfile, src/main/java/ongjong/namanmoo/config/OpenAiConfig.java
=> 🚨 OPENAI_API 도커 실행 환경 설정 🚨

Dockerfile, src/main/java/ongjong/namanmoo/controller/ChallengeController.java
=> 🚨 OPENAI_API 도커 실행 환경 설정 🚨 

.github/workflows/Spring Boot CI-CD.yml, src/main/resources/application.yml
=> [CI/CD] env setting

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-53] 전달 값 수정

src/main/java/ongjong/namanmoo/config/AsyncConfig.java, src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-34] 음성 분할 비동기식으로 변경

src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> [TSK-54] lucky die from get current challenge

src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java
=> [TSK-54] fix get current challenge

src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java
=> [TSK-53] 리캡 사진 null 제외

src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java
=> [TSK-53] 리캡 사진 중복 제외

src/main/java/ongjong/namanmoo/controller/ChallengeController.java
=> [TSK-54] fix current challenge

src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/service/ChallengeDataInit.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java
=> [TSK-54] fix challenge date

src/main/java/ongjong/namanmoo/controller/RecapController.java
=> [TSK-34] silenceDuration -> 0.1

.gitignore, build.gradle, src/main/java/ongjong/namanmoo/config/FirebaseConfig.java, src/main/java/ongjong/namanmoo/controller/NotificationController.java, src/main/java/ongjong/namanmoo/dto/fcm/NotificationRequest.java, src/main/java/ongjong/namanmoo/dto/fcm/TokenRequest.java, src/main/java/ongjong/namanmoo/service/FCMInitializer.java, src/main/java/ongjong/namanmoo/service/FCMService.java, src/main/resources/application.yml
=> Feature/tsk 56/alarm

.dockerignore, .github/workflows/Spring Boot CI-CD.yml, Dockerfile, src/main/java/ongjong/namanmoo/config/FirebaseConfig.java, src/main/resources/application.yml
=> [TSK-53] Firebase 환경 변수 설정 

.dockerignore, .github/workflows/Spring Boot CI-CD.yml, .gitignore, Dockerfile, build.gradle, src/main/java/ongjong/namanmoo/config/FirebaseConfig.java, src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/controller/NotificationController.java, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/dto/fcm/NotificationRequest.java, src/main/java/ongjong/namanmoo/dto/fcm/TokenRequest.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java, src/main/java/ongjong/namanmoo/service/ChallengeDataInit.java, src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java, src/main/java/ongjong/namanmoo/service/FCMInitializer.java, src/main/java/ongjong/namanmoo/service/FCMService.java, src/main/java/ongjong/namanmoo/service/LuckyService.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java, src/main/resources/application.yml
=> [TSK-53] Firebase 환경 변수 설정

Dockerfile, src/main/java/ongjong/namanmoo/config/FirebaseConfig.java
=> 🚨firebase CI/CD🚨

.dockerignore, .github/workflows/Spring Boot CI-CD.yml, Dockerfile
=> 🚨firebase CI/CD🚨 

.dockerignore, .github/workflows/Spring Boot CI-CD.yml, Dockerfile
=> 🚨🚨firebase CI/CD🚨🚨

src/main/java/ongjong/namanmoo/service/LuckyService.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> [TSK-57] Create calculateLuckyStatus for presentation

.gitignore, src/main/java/ongjong/namanmoo/controller/RecapController.java, src/main/java/ongjong/namanmoo/service/AnswerServiceImpl.java
=> gitignore update

src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> [TSK-57] 시연용 스테이터스

.github/workflows/dongyeop CI-CD.yml
=> Create dongyeop CI-CD.yml

.github/workflows/Spring Boot CI-CD.yml
=> Update Spring Boot CI-CD.yml

.github/workflows/Spring Boot CI-CD.yml, .github/workflows/dongyeop CI-CD.yml
=> Dongyeoppp patch 1

src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/LuckyServiceImpl.java
=> [TSK-55] 시연 리허설 준비

src/main/java/ongjong/namanmoo/service/ChallengeServiceImpl.java
=> [TSK-55] 모두 가장 빨리 답한 챌린지 수정

.github/workflows/Spring Boot CI-CD.yml, src/main/java/ongjong/namanmoo/controller/ChallengeController.java, src/main/java/ongjong/namanmoo/service/PerformanceAspect.java, src/main/java/ongjong/namanmoo/service/SharedFileService.java
=> [TSK-55] 화상통화 결과 저장 API 응답시간 측정용
